language: c
dist: trusty

addons:
  apt:
    packages:
      - mingw-w64
      - cmake
      - valgrind
      - wine

matrix:
  include:
  - env:
      - TASK="lab0"
  - env:
      - TASK="lab1-0"
  - env:
      - TASK="lab1-1"
  - env:
      - TASK="lab2"
  - env:
      - TASK="lab3-0"
  - env:
      - TASK="lab3-1"
  - env:
      - TASK="lab4"
  - env:
      - TASK="lab5"
  - env:
      - TASK="lab6"
  - env:
      - TASK="lab7"
  - env:
      - TASK="lab8-0"
  - env:
      - TASK="lab8-1"
  - env:
      - TASK="lab9"

script:
  - sudo sysctl -w vm.mmap_min_addr=0
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../modules/mingw-toolchain.cmake ../${TASK}/
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - head -c 4096 in.txt || true

# - ctest -VV -T memcheck
# valgrind doesn't work with wine (╯°□°）╯︵ ┻━┻ (but it should)
  - cp in.txt ../ && rm -rf * && mv ../in.txt . || true
  - cmake ../${TASK}/
  - make
  - valgrind 
    --leak-check=full 
    --track-fds=yes 
    --error-exitcode=1 
    ./${TASK} < in.txt
